server:
  port: 8101

spring:
  application:
    name: admin-server
eureka:
  instance:
    prefer-ip-address: true #\u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u8FD8\u4F7F\u7528\u670D\u52A1\u7684IP\u5730\u5740
    instance-id: admin-server-8101 # Eureka\u754C\u9762\u4E0A\u7684\u670D\u52A1\u540D\u79F0\u5BF9\u5E94\u7684STATUS\u5730\u5740
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
