server:
  port: 9101

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8101

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file: /admin-client.log
